Completed css-canvas-medical - Jonathan Chiang
J0N-C/m1-0621-code-solutions pull request #23
Opened 2021-07-09 03:39 UTC by J0N-C

![css-canvas-medical-home-pt1](https://user-images.githubusercontent.com/64382900/125019733-61449700-e02c-11eb-9b56-b24aebb730c4.JPG)
![css-canvas-medical-home-pt2](https://user-images.githubusercontent.com/64382900/125019740-6275c400-e02c-11eb-9e49-75abd07fcf66.JPG)

2021-07-09 03:53 UTC, Zhiwutian requested changes
small update!

2021-07-09 03:53 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +<header>
This element and its children need to be placed within the `body` tags

2021-07-09 03:58 UTC, Zhiwutian approved these changes
👍🏼

2021-07-12 04:45 UTC, J0N-C commented
![css-canvas-medical-product](https://user-images.githubusercontent.com/64382900/125232313-36a74800-e291-11eb-803e-910d4bd6f653.JPG)
![css-canvas-medical-implementation](https://user-images.githubusercontent.com/64382900/125232316-37d87500-e291-11eb-971b-0b4626480c97.JPG)
![css-canvas-medical-about](https://user-images.githubusercontent.com/64382900/125232330-3eff8300-e291-11eb-88e8-7b27cbdcd0b3.JPG)
![css-canvas-medical-blog](https://user-images.githubusercontent.com/64382900/125232335-4030b000-e291-11eb-88ff-74c9b17445c1.JPG)
![css-canvas-medical-contact](https://user-images.githubusercontent.com/64382900/125232339-4161dd00-e291-11eb-9453-1fd0d6f97126.JPG)

2021-07-13 02:21 UTC, merged